/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { HttpClient, HttpContext, HttpResponse } from '@angular/common/http';
import { Observable } from 'rxjs';
import { filter, map } from 'rxjs/operators';
import { StrictHttpResponse } from '../../strict-http-response';
import { RequestBuilder } from '../../request-builder';

import { LinkPayementRespons } from '../../models/link-payement-respons';
import { TransactionRequest } from '../../models/transaction-request';

export interface GetPaymentLink$Params {
  request: TransactionRequest;
}

export function getPaymentLink(http: HttpClient, rootUrl: string, params: GetPaymentLink$Params, context?: HttpContext): Observable<StrictHttpResponse<LinkPayementRespons>> {
  const rb = new RequestBuilder(rootUrl, getPaymentLink.PATH, 'post');
  if (params) {
    rb.query('request', params.request, {});
  }

  return http.request(
    rb.build({ responseType: 'json', accept: 'application/json', context })
  ).pipe(
    filter((r: any): r is HttpResponse<any> => r instanceof HttpResponse),
    map((r: HttpResponse<any>) => {
      return r as StrictHttpResponse<LinkPayementRespons>;
    })
  );
}

getPaymentLink.PATH = '/payment/link';
