/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { HttpClient, HttpContext, HttpResponse } from '@angular/common/http';
import { Observable } from 'rxjs';
import { filter, map } from 'rxjs/operators';
import { StrictHttpResponse } from '../../strict-http-response';
import { RequestBuilder } from '../../request-builder';

import { PanneauResponse } from '../../models/panneau-response';

export interface PanneauFindById$Params {
}

export function panneauFindById(http: HttpClient, rootUrl: string, params?: PanneauFindById$Params, context?: HttpContext): Observable<StrictHttpResponse<PanneauResponse>> {
  const rb = new RequestBuilder(rootUrl, panneauFindById.PATH, 'get');
  if (params) {
  }

  return http.request(
    rb.build({ responseType: 'json', accept: 'application/json', context })
  ).pipe(
    filter((r: any): r is HttpResponse<any> => r instanceof HttpResponse),
    map((r: HttpResponse<any>) => {
      return r as StrictHttpResponse<PanneauResponse>;
    })
  );
}

panneauFindById.PATH = '/panneau/{panneau-id}';
