/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { HttpClient, HttpContext, HttpResponse } from '@angular/common/http';
import { Observable } from 'rxjs';
import { filter, map } from 'rxjs/operators';
import { StrictHttpResponse } from '../../strict-http-response';
import { RequestBuilder } from '../../request-builder';

import { PanneauResponse } from '../../models/panneau-response';
import { PanneauRquest } from '../../models/panneau-rquest';

export interface UpdatePanneauById1$Params {
  'panneau-id': number;
      body: PanneauRquest
}

export function updatePanneauById1(http: HttpClient, rootUrl: string, params: UpdatePanneauById1$Params, context?: HttpContext): Observable<StrictHttpResponse<PanneauResponse>> {
  const rb = new RequestBuilder(rootUrl, updatePanneauById1.PATH, 'put');
  if (params) {
    rb.path('panneau-id', params['panneau-id'], {});
    rb.body(params.body, 'application/json');
  }

  return http.request(
    rb.build({ responseType: 'json', accept: 'application/json', context })
  ).pipe(
    filter((r: any): r is HttpResponse<any> => r instanceof HttpResponse),
    map((r: HttpResponse<any>) => {
      return r as StrictHttpResponse<PanneauResponse>;
    })
  );
}

updatePanneauById1.PATH = '/panneau/update/{panneau-id}';
