/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { HttpClient, HttpContext, HttpResponse } from '@angular/common/http';
import { Observable } from 'rxjs';
import { filter, map } from 'rxjs/operators';
import { StrictHttpResponse } from '../../strict-http-response';
import { RequestBuilder } from '../../request-builder';

import { PageResponsePanneauResponse } from '../../models/page-response-panneau-response';

export interface GetAllPanneauxLibreByBoulevard$Params {
  boulevard: string;
  page?: number;
  size?: number;
}

export function getAllPanneauxLibreByBoulevard(http: HttpClient, rootUrl: string, params: GetAllPanneauxLibreByBoulevard$Params, context?: HttpContext): Observable<StrictHttpResponse<PageResponsePanneauResponse>> {
  const rb = new RequestBuilder(rootUrl, getAllPanneauxLibreByBoulevard.PATH, 'get');
  if (params) {
    rb.path('boulevard', params.boulevard, {});
    rb.query('page', params.page, {});
    rb.query('size', params.size, {});
  }

  return http.request(
    rb.build({ responseType: 'json', accept: 'application/json', context })
  ).pipe(
    filter((r: any): r is HttpResponse<any> => r instanceof HttpResponse),
    map((r: HttpResponse<any>) => {
      return r as StrictHttpResponse<PageResponsePanneauResponse>;
    })
  );
}

getAllPanneauxLibreByBoulevard.PATH = '/panneau/panneaux-libre/boulevard/{boulevard}';
