/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { HttpClient, HttpContext, HttpResponse } from '@angular/common/http';
import { Observable } from 'rxjs';
import { filter, map } from 'rxjs/operators';
import { StrictHttpResponse } from '../../strict-http-response';
import { RequestBuilder } from '../../request-builder';

import { FactureResponse } from '../../models/facture-response';

export interface GetFactureByAbonnementid$Params {
  abonnementId: number | null;
}

export function getFactureByAbonnementid(http: HttpClient, rootUrl: string, params: GetFactureByAbonnementid$Params, context?: HttpContext): Observable<StrictHttpResponse<FactureResponse>> {
  const rb = new RequestBuilder(rootUrl, getFactureByAbonnementid.PATH, 'get');
  if (params) {
    rb.query('abonnementId', params.abonnementId, {});
  }

  return http.request(
    rb.build({ responseType: 'json', accept: 'application/json', context })
  ).pipe(
    filter((r: any): r is HttpResponse<any> => r instanceof HttpResponse),
    map((r: HttpResponse<any>) => {
      return r as StrictHttpResponse<FactureResponse>;
    })
  );
}

getFactureByAbonnementid.PATH = '/facture/get-facture-by-abonnement';
