/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { HttpClient, HttpContext, HttpResponse } from '@angular/common/http';
import { Observable } from 'rxjs';
import { filter, map } from 'rxjs/operators';
import { StrictHttpResponse } from '../../strict-http-response';
import { RequestBuilder } from '../../request-builder';

import { Facture } from '../../models/facture';

export interface GetFactureByTrans$Params {
  transId: string | null;
}

export function getFactureByTrans(http: HttpClient, rootUrl: string, params: GetFactureByTrans$Params, context?: HttpContext): Observable<StrictHttpResponse<Facture>> {
  const rb = new RequestBuilder(rootUrl, getFactureByTrans.PATH, 'get');
  if (params) {
    rb.query('transId', params.transId, {});
  }

  return http.request(
    rb.build({ responseType: 'json', accept: 'application/json', context })
  ).pipe(
    filter((r: any): r is HttpResponse<any> => r instanceof HttpResponse),
    map((r: HttpResponse<any>) => {
      return r as StrictHttpResponse<Facture>;
    })
  );
}

getFactureByTrans.PATH = '/facture/get-facture';
