/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { HttpClient, HttpContext, HttpResponse } from '@angular/common/http';
import { Observable } from 'rxjs';
import { filter, map } from 'rxjs/operators';
import { StrictHttpResponse } from '../../strict-http-response';
import { RequestBuilder } from '../../request-builder';

import { NotificationRequestBody } from '../../models/notification-request-body';

export interface CheckStatusNotify$Params {
  'x-token': string;
  'cpm_trans_id ': string;
      body: NotificationRequestBody
}

export function checkStatusNotify(http: HttpClient, rootUrl: string, params: CheckStatusNotify$Params, context?: HttpContext): Observable<StrictHttpResponse<{
}>> {
  const rb = new RequestBuilder(rootUrl, checkStatusNotify.PATH, 'post');
  if (params) {
    rb.header('x-token', params['x-token'], {});
    rb.query('cpm_trans_id ', params['cpm_trans_id '], {});
    rb.body(params.body, 'application/json');
  }

  return http.request(
    rb.build({ responseType: 'json', accept: 'application/json', context })
  ).pipe(
    filter((r: any): r is HttpResponse<any> => r instanceof HttpResponse),
    map((r: HttpResponse<any>) => {
      return r as StrictHttpResponse<{
      }>;
    })
  );
}

checkStatusNotify.PATH = '/payment/notification';
