/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

export interface AbonnementRequest {
  Panneau?: Array<number>;
  dateAbn: string;
  dateDebut: string;
  dateFin: string;
  description: string;
  prix: number;
}
