/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

export interface AbonnementResponse {
  actif?: boolean;
  dateAbn?: string;
  dateDebut?: string;
  dateFin?: string;
  description?: string;
  duree?: number;
  id?: number;
  mtnPayer?: number;
  mtnRest?: number;
  nbrJrs?: number;
  picture?: Array<Array<string>>;
  prix?: number;
  user?: string;
  valid?: boolean;
}
