/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { Panneau } from '../models/panneau';
export interface Boulevard {
  createdAt?: string;
  createdBy?: number;
  id?: number;
  name?: string;
  nbrDePanneau?: number;
  nombreDePanneau?: number;
  panneaux?: Array<Panneau>;
  updateAt?: string;
  updateBy?: number;
}
