/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

export interface LigneAbonnementResponse {
  boulevardName?: string;
  emplacement?: string;
  nbrFace?: number;
  panneauId?: number;
  picture?: Array<string>;
  price?: number;
  printPrice?: number;
  taille?: number;
  type?: string;
}
