/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { Data } from '../models/data';
export interface LinkPayementRespons {
  api_response_id?: string;
  code?: string;
  data?: Data;
  description?: string;
  message?: string;
}
