/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

export interface PanneauRquest {
  boulevard_id?: number;
  localisation: string;
  nbRFace?: number;
  printPrice?: number;
  prixMensuel?: number;
  taille?: number;
  typePanneau: string;
}
