/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

export interface PanneauResponse {
  boulevardName?: string;
  id?: number;
  localisation?: string;
  nbrFace?: number;
  occuped?: boolean;
  printPrice?: number;
  prixMensuel?: number;
  taille?: number;
  enabled?:boolean
  typePanneauLibele?: string;
}
