/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { Boulevard } from '../models/boulevard';
import { TypePanneau } from '../models/type-panneau';
export interface PanneauResponse {
  boulevard?: Boulevard;
  id?: number;
  localisation?: string;
  nbrFace?: number;
  occuped?: boolean;
  printPrice?: number;
  prixMensuel?: number;
  taille?: number;
  typePanneau?: TypePanneau;
}
