/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

export interface RegistrationFormRequest {
  confirmPassword: string;
  email: string;
  nonUtilisateur: string;
  numero: string;
  password: string;
}
