/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

export interface TransactionResponse {
  abonnementId?: number;
  amount?: number;
  currency?: 'XOF (West African CFA Franc)' | 'XAF (Central African CFA Franc)' | 'CDF (Congolese Franc)' | 'GNF (Guinean Franc)' | 'USD (United States Dollar)';
  localDateTimeTrans?: string;
  payment_method?: string;
  status?: string;
  userEmail?: string;
  username?: string;
}
