/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { Panneau } from '../models/panneau';
export interface TypePanneau {
  id?: number;
  libelet?: string;
  panneaux?: Array<Panneau>;
}
