/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { Role } from '../models/role';
export interface UserResponse {
  accountLocked: boolean;
  createdAT: string;
  email: string;
  enabled: boolean;
  fidelisation: boolean;
  id: number;
  nonUtilisateur: string;
  numero: string;
  roleList: Array<Role>;
  updateAt: string;
}
