/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { HttpClient, HttpContext, HttpResponse } from '@angular/common/http';
import { Observable } from 'rxjs';
import { filter, map } from 'rxjs/operators';
import { StrictHttpResponse } from '../../strict-http-response';
import { RequestBuilder } from '../../request-builder';

import { BoulevardResponse } from '../../models/boulevard-response';

export interface BoulevardFindById$Params {
  'boulevard-id': number;
}

export function boulevardFindById(http: HttpClient, rootUrl: string, params: BoulevardFindById$Params, context?: HttpContext): Observable<StrictHttpResponse<BoulevardResponse>> {
  const rb = new RequestBuilder(rootUrl, boulevardFindById.PATH, 'get');
  if (params) {
    rb.path('boulevard-id', params['boulevard-id'], {});
  }

  return http.request(
    rb.build({ responseType: 'json', accept: 'application/json', context })
  ).pipe(
    filter((r: any): r is HttpResponse<any> => r instanceof HttpResponse),
    map((r: HttpResponse<any>) => {
      return r as StrictHttpResponse<BoulevardResponse>;
    })
  );
}

boulevardFindById.PATH = '/boulevard/{boulevard-id}';
