/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { HttpClient, HttpContext, HttpResponse } from '@angular/common/http';
import { Observable } from 'rxjs';
import { filter, map } from 'rxjs/operators';
import { StrictHttpResponse } from '../../strict-http-response';
import { RequestBuilder } from '../../request-builder';

import { BoulevardResponse } from '../../models/boulevard-response';

export interface GetBoulByPanneau$Params {
  panneauId: number;
}

export function getBoulByPanneau(http: HttpClient, rootUrl: string, params: GetBoulByPanneau$Params, context?: HttpContext): Observable<StrictHttpResponse<BoulevardResponse>> {
  const rb = new RequestBuilder(rootUrl, getBoulByPanneau.PATH, 'get');
  if (params) {
    rb.query('panneauId', params.panneauId, {});
  }

  return http.request(
    rb.build({ responseType: 'json', accept: 'application/json', context })
  ).pipe(
    filter((r: any): r is HttpResponse<any> => r instanceof HttpResponse),
    map((r: HttpResponse<any>) => {
      return r as StrictHttpResponse<BoulevardResponse>;
    })
  );
}

getBoulByPanneau.PATH = '/boulevard/boulevard-by-panneau';
