/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { HttpClient, HttpContext, HttpResponse } from '@angular/common/http';
import { Observable } from 'rxjs';
import { filter, map } from 'rxjs/operators';
import { StrictHttpResponse } from '../../strict-http-response';
import { RequestBuilder } from '../../request-builder';

import { AbonnementResponse } from '../../models/abonnement-response';

export interface GetAbonnementById$Params {
  'abonnement-id': number;
}

export function getAbonnementById(http: HttpClient, rootUrl: string, params: GetAbonnementById$Params, context?: HttpContext): Observable<StrictHttpResponse<AbonnementResponse>> {
  const rb = new RequestBuilder(rootUrl, getAbonnementById.PATH, 'get');
  if (params) {
    rb.path('abonnement-id', params['abonnement-id'], {});
  }

  return http.request(
    rb.build({ responseType: 'json', accept: 'application/json', context })
  ).pipe(
    filter((r: any): r is HttpResponse<any> => r instanceof HttpResponse),
    map((r: HttpResponse<any>) => {
      return r as StrictHttpResponse<AbonnementResponse>;
    })
  );
}

getAbonnementById.PATH = '/abonnement/{abonnement-id}';
