/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { Image } from '../models/image';
import { LigneAbonnement } from '../models/ligne-abonnement';
import { Transaction } from '../models/transaction';
import { User } from '../models/user';
export interface Abonnement {
  actif?: boolean;
  createdAt?: string;
  createdBy?: number;
  dateAbn?: string;
  dateDebut?: string;
  dateFin?: string;
  description?: string;
  duree?: number;
  dureeAbonnement?: number;
  id?: number;
  images?: Array<Image>;
  ligneAbonnements?: Array<LigneAbonnement>;
  montantTotalAbonnement?: number;
  mtnPayer?: number;
  mtnRest?: number;
  niveauAbn?: 'TOTAL' | 'PARTIEL';
  prix?: number;
  transactionsList?: Array<Transaction>;
  updateAt?: string;
  updateBy?: number;
  user?: User;
  valid?: boolean;
}
