/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { Role } from '../models/role';
export interface AdminFormRequest {
  email: string;
  nonUtilisateur: string;
  numero: string;
  password: string;
  userRole: Array<Role>;
}
