/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

export interface FactureResponse {
  abonnementId?: number;
  dateAbn?: string;
  dateDebAbn?: string;
  dateFinAbn?: string;
  datePayment?: string;
  id?: number;
  mtnPayer?: number;
  mtnRestant?: number;
  mtnTotal?: number;
  reference?: string;
  transaction?: string;
}
