/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

export interface ImageResponse {
  dateDebut?: string;
  dateFin?: string;
  panneauId?: number;
  picture?: Array<string>;
}
