/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { Abonnement } from '../models/abonnement';
export interface Image {
  abonnement?: Abonnement;
  createdAt?: string;
  createdBy?: number;
  id?: number;
  nomImage?: string;
  updateAt?: string;
  updateBy?: number;
}
