/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { Abonnement } from '../models/abonnement';
import { LigneAbonnement } from '../models/ligne-abonnement';
export interface Image {
  abonnement?: Abonnement;
  createdAt?: string;
  createdBy?: number;
  dateDebut?: string;
  dateFin?: string;
  id?: number;
  ligneAbonnements?: Array<LigneAbonnement>;
  nomImage?: string;
  updateAt?: string;
  updateBy?: number;
}
