/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { Abonnement } from '../models/abonnement';
import { Image } from '../models/image';
import { Panneau } from '../models/panneau';
export interface LigneAbonnement {
  abonnement?: Abonnement;
  createdAt?: string;
  createdBy?: number;
  dateDebut?: string;
  dateFin?: string;
  id?: number;
  panneau?: Panneau;
  theImage?: Image;
  updateAt?: string;
  updateBy?: number;
}
