/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

export interface MessageResponse {
  abonnementId?: number;
  localDateTime?: string;
  message?: string;
  receiverMail?: string;
  type?: 'CONFIRMATION' | 'VERIFICATION';
}
