/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

export interface NotificationRequestBody {
  cel_phone_num?: string;
  cpm_amount?: number;
  cpm_currency?: string;
  cpm_custom?: string;
  cpm_designation?: string;
  cpm_error_message?: string;
  cpm_language?: string;
  cpm_page_action?: string;
  cpm_payment_config?: string;
  cpm_phone_prefixe?: string;
  cpm_site_id?: string;
  cpm_trans_date?: string;
  cpm_trans_id?: string;
  cpm_version?: string;
  payment_method?: string;
  signature?: string;
}
