/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { UserResponse } from '../models/user-response';
export interface PageResponseUserResponse {
  content?: Array<UserResponse>;
  firstPage?: boolean;
  lastPage?: boolean;
  nomber?: number;
  size?: number;
  totalElements?: number;
  totalPage?: number;
}
