/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { AbonnementResponse } from '../models/abonnement-response';
export interface PageResponseAbonnementResponse {
  content?: Array<AbonnementResponse>;
  firstPage?: boolean;
  lastPage?: boolean;
  nomber?: number;
  size?: number;
  totalElements?: number;
  totalPage?: number;
}
