/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { BoulevardResponse } from '../models/boulevard-response';
export interface PageResponseBoulevardResponse {
  content?: Array<BoulevardResponse>;
  firstPage?: boolean;
  lastPage?: boolean;
  nomber?: number;
  size?: number;
  totalElements?: number;
  totalPage?: number;
}
