/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { PanneauResponse } from '../models/panneau-response';
export interface PageResponsePanneauResponse {
  content?: Array<PanneauResponse>;
  firstPage?: boolean;
  lastPage?: boolean;
  nomber?: number;
  size?: number;
  totalElements?: number;
  totalPage?: number;
}
