/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { Boulevard } from '../models/boulevard';
import { LigneAbonnement } from '../models/ligne-abonnement';
import { TypePanneau } from '../models/type-panneau';
export interface Panneau {
  boulevard?: Boulevard;
  createdAt?: string;
  createdBy?: number;
  id?: number;
  ligneAbonnements?: Array<LigneAbonnement>;
  localisation?: string;
  nbreFace?: number;
  occuped?: boolean;
  printPrice?: number;
  prixMensuel?: number;
  taille?: number;
  typePanneau?: TypePanneau;
  updateAt?: string;
  updateBy?: number;
}
