/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

export interface TransactionRequest {
  abonnementId?: number;
  amount?: number;
  chanel?: 'ALL' | 'MOBILE_MONEY' | 'CREDIT_CARD' | 'WALLET';
  currency?: 'XOF (West African CFA Franc)' | 'XAF (Central African CFA Franc)' | 'CDF (Congolese Franc)' | 'GNF (Guinean Franc)' | 'USD (United States Dollar)';
  dateTrans?: string;
  description?: string;
}
