/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { Panneau } from '../models/panneau';
export interface TypePanneau {
  createdAt?: string;
  createdBy?: number;
  id?: number;
  libelet?: string;
  panneaux?: Array<Panneau>;
  updateAt?: string;
  updateBy?: number;
}
