/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { GrantedAuthority } from '../models/granted-authority';
export interface User {
  accountLocked?: boolean;
  accountNonExpired?: boolean;
  accountNonLocked?: boolean;
  authorities?: Array<GrantedAuthority>;
  createdAT?: string;
  credentialsNonExpired?: boolean;
  email?: string;
  enabled?: boolean;
  fidelisation?: boolean;
  id?: number;
  name?: string;
  nonUtilisateur?: string;
  numero?: string;
  password?: string;
  updateAt?: string;
  username?: string;
}
