/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { HttpClient, HttpContext, HttpResponse } from '@angular/common/http';
import { Observable } from 'rxjs';
import { filter, map } from 'rxjs/operators';
import { StrictHttpResponse } from '../../strict-http-response';
import { RequestBuilder } from '../../request-builder';

import { LigneAbonnementResponse } from '../../models/ligne-abonnement-response';

export interface GetAllLigneAbn1$Params {
  abonnementId: number;
}

export function getAllLigneAbn1(http: HttpClient, rootUrl: string, params: GetAllLigneAbn1$Params, context?: HttpContext): Observable<StrictHttpResponse<Array<LigneAbonnementResponse>>> {
  const rb = new RequestBuilder(rootUrl, getAllLigneAbn1.PATH, 'get');
  if (params) {
    rb.query('abonnementId', params.abonnementId, {});
  }

  return http.request(
    rb.build({ responseType: 'json', accept: 'application/json', context })
  ).pipe(
    filter((r: any): r is HttpResponse<any> => r instanceof HttpResponse),
    map((r: HttpResponse<any>) => {
      return r as StrictHttpResponse<Array<LigneAbonnementResponse>>;
    })
  );
}

getAllLigneAbn1.PATH = '/line-abonnement/all-by-user';
