/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { HttpClient, HttpContext, HttpResponse } from '@angular/common/http';
import { Observable } from 'rxjs';
import { filter, map } from 'rxjs/operators';
import { StrictHttpResponse } from '../../strict-http-response';
import { RequestBuilder } from '../../request-builder';

import { ImageResponse } from '../../models/image-response';

export interface FindAllImages$Params {
  abonnementId: number | undefined;
}

export function findAllImages(http: HttpClient, rootUrl: string, params: FindAllImages$Params, context?: HttpContext): Observable<StrictHttpResponse<Array<ImageResponse>>> {
  const rb = new RequestBuilder(rootUrl, findAllImages.PATH, 'get');
  if (params) {
    rb.query('abonnementId', params.abonnementId, {});
  }

  return http.request(
    rb.build({ responseType: 'json', accept: 'application/json', context })
  ).pipe(
    filter((r: any): r is HttpResponse<any> => r instanceof HttpResponse),
    map((r: HttpResponse<any>) => {
      return r as StrictHttpResponse<Array<ImageResponse>>;
    })
  );
}

findAllImages.PATH = '/image';
