/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { HttpClient, HttpContext, HttpResponse } from '@angular/common/http';
import { Observable } from 'rxjs';
import { filter, map } from 'rxjs/operators';
import { StrictHttpResponse } from '../../strict-http-response';
import { RequestBuilder } from '../../request-builder';

import { BoulevardResponse } from '../../models/boulevard-response';
import { BoulevarRequest } from '../../models/boulevar-request';

export interface UpdateBoulevard$Params {
  'boulevard-id': number;
      body: BoulevarRequest
}

export function updateBoulevard(http: HttpClient, rootUrl: string, params: UpdateBoulevard$Params, context?: HttpContext): Observable<StrictHttpResponse<BoulevardResponse>> {
  const rb = new RequestBuilder(rootUrl, updateBoulevard.PATH, 'put');
  if (params) {
    rb.path('boulevard-id', params['boulevard-id'], {});
    rb.body(params.body, 'application/json');
  }

  return http.request(
    rb.build({ responseType: 'json', accept: 'application/json', context })
  ).pipe(
    filter((r: any): r is HttpResponse<any> => r instanceof HttpResponse),
    map((r: HttpResponse<any>) => {
      return r as StrictHttpResponse<BoulevardResponse>;
    })
  );
}

updateBoulevard.PATH = '/boulevard/update/{boulevard-id}';
