/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { HttpClient, HttpContext } from '@angular/common/http';
import { Injectable } from '@angular/core';
import { Observable } from 'rxjs';
import { map } from 'rxjs/operators';

import { BaseService } from '../base-service';
import { ApiConfiguration } from '../api-configuration';
import { StrictHttpResponse } from '../strict-http-response';

import { FactureResponse } from '../models/facture-response';
import { getFactureByAbonnementid } from '../fn/facture-controler/get-facture-by-abonnementid';
import { GetFactureByAbonnementid$Params } from '../fn/facture-controler/get-facture-by-abonnementid';
import { getFactureByTrans } from '../fn/facture-controler/get-facture-by-trans';
import { GetFactureByTrans$Params } from '../fn/facture-controler/get-facture-by-trans';

@Injectable({ providedIn: 'root' })
export class FactureControlerService extends BaseService {
  constructor(config: ApiConfiguration, http: HttpClient) {
    super(config, http);
  }

  /** Path part for operation `getFactureByTrans()` */
  static readonly GetFactureByTransPath = '/facture/get-facture';

  /**
   * This method provides access to the full `HttpResponse`, allowing access to response headers.
   * To access only the response body, use `getFactureByTrans()` instead.
   *
   * This method doesn't expect any request body.
   */
  getFactureByTrans$Response(params: GetFactureByTrans$Params, context?: HttpContext): Observable<StrictHttpResponse<FactureResponse>> {
    return getFactureByTrans(this.http, this.rootUrl, params, context);
  }

  /**
   * This method provides access only to the response body.
   * To access the full response (for headers, for example), `getFactureByTrans$Response()` instead.
   *
   * This method doesn't expect any request body.
   */
  getFactureByTrans(params: GetFactureByTrans$Params, context?: HttpContext): Observable<FactureResponse> {
    return this.getFactureByTrans$Response(params, context).pipe(
      map((r: StrictHttpResponse<FactureResponse>): FactureResponse => r.body)
    );
  }

  /** Path part for operation `getFactureByAbonnementid()` */
  static readonly GetFactureByAbonnementidPath = '/facture/get-facture-by-abonnement';

  /**
   * This method provides access to the full `HttpResponse`, allowing access to response headers.
   * To access only the response body, use `getFactureByAbonnementid()` instead.
   *
   * This method doesn't expect any request body.
   */
  getFactureByAbonnementid$Response(params: GetFactureByAbonnementid$Params, context?: HttpContext): Observable<StrictHttpResponse<FactureResponse>> {
    return getFactureByAbonnementid(this.http, this.rootUrl, params, context);
  }

  /**
   * This method provides access only to the response body.
   * To access the full response (for headers, for example), `getFactureByAbonnementid$Response()` instead.
   *
   * This method doesn't expect any request body.
   */
  getFactureByAbonnementid(params: GetFactureByAbonnementid$Params, context?: HttpContext): Observable<FactureResponse> {
    return this.getFactureByAbonnementid$Response(params, context).pipe(
      map((r: StrictHttpResponse<FactureResponse>): FactureResponse => r.body)
    );
  }

}
