/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { HttpClient, HttpContext } from '@angular/common/http';
import { Injectable } from '@angular/core';
import { Observable } from 'rxjs';
import { map } from 'rxjs/operators';

import { BaseService } from '../base-service';
import { ApiConfiguration } from '../api-configuration';
import { StrictHttpResponse } from '../strict-http-response';

import { getAllLigneAbn } from '../fn/ligne-abonnment/get-all-ligne-abn';
import { GetAllLigneAbn$Params } from '../fn/ligne-abonnment/get-all-ligne-abn';
import { LigneAbonnementResponse } from '../models/ligne-abonnement-response';

@Injectable({ providedIn: 'root' })
export class LigneAbonnmentService extends BaseService {
  constructor(config: ApiConfiguration, http: HttpClient) {
    super(config, http);
  }

  /** Path part for operation `getAllLigneAbn()` */
  static readonly GetAllLigneAbnPath = '/line-abonnement/all';

  /**
   * This method provides access to the full `HttpResponse`, allowing access to response headers.
   * To access only the response body, use `getAllLigneAbn()` instead.
   *
   * This method doesn't expect any request body.
   */
  getAllLigneAbn$Response(params: GetAllLigneAbn$Params, context?: HttpContext): Observable<StrictHttpResponse<Array<LigneAbonnementResponse>>> {
    return getAllLigneAbn(this.http, this.rootUrl, params, context);
  }

  /**
   * This method provides access only to the response body.
   * To access the full response (for headers, for example), `getAllLigneAbn$Response()` instead.
   *
   * This method doesn't expect any request body.
   */
  getAllLigneAbn(params: GetAllLigneAbn$Params, context?: HttpContext): Observable<Array<LigneAbonnementResponse>> {
    return this.getAllLigneAbn$Response(params, context).pipe(
      map((r: StrictHttpResponse<Array<LigneAbonnementResponse>>): Array<LigneAbonnementResponse> => r.body)
    );
  }

}
